### ISSUE TITLE
Unexpected resolutions in node_modules

### ISSUE THREAD

**Issue by bpevs** [elastic/webpack-directory-name-as-main#1]
I got this warning while using your plugin and superagent at the same time:

```
WARNING in ./~/superagent/superagent.js
Critical dependencies:
1:441-448 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/superagent/superagent.js 1:441-448
```

Didn't spend a ton of time looking at it, but I figure it basically didn't expect to resolve that file.  I just basically placed an `if(!!directory.match(/node_modules/)) return done();` and that seemed to work for me.  I'm not super comfortable with Webpack, so I'm not sure if that would problems I wouldn't expect, but I'm happy to look into it more, make sure it's ok, and send you a PR if you think that would be useful.

**Comment by spalger** [comment]
Hmm, perhaps that isn't a bad idea. Ideally the default resolution would always take precedence and this module would only kick into effect if all else fails.

If you send a pr though I'd accept it.

**Comment by liady** [comment]
@spalger any news on this issue? I have the same problem with the `prop-types` and `react-create-class` packages (both contain a pre-built file with the same name).
Is there a reason the `index.js` isn't being identified there?

**Comment by spalger** [comment]
@liady what version are you using, that should be fixed in v2

**Comment by liady** [comment]
@spalger I'm using v1.0.0, I see that currently it's the latest release...

**Comment by spalger** [comment]
@liady oh, the package was renamed to `@elastic/webpack-directory-name-as-main`

**Comment by liady** [comment]
@spalger great, it works in v2. Thanks!
